Weather view app
firstpj/my-react-webapp pull request #1
Opened 2023-09-14 23:57 UTC by firstpj

In this milestone, I have accomplished the following tasks:

1. Developed a home page that displays numeric values for various countries, sourced from an API.

2. Implemented functionality where clicking or tapping on a country card directs the user to a details page.

3. On the details page, the web application fetches data from the API to present comprehensive information about the selected country.

4. Incorporated a "Back" button (<) that allows users to easily navigate back to the home page.

About the project:

The project is a single-page application (SPA) constructed using React and Redux.

Data obtained from the API is stored in the Redux store for efficient management.

Each page, including the main page and individual item pages, possesses a distinct route within the SPA.

The project is deployed and accessible online through Netlify.

2023-09-15 17:37 UTC, Munsa1 requested changes
Hi @firstpj, 

Good job so far!
There are some issues that you still need to work on to prepare your project for the final evaluation but you are almost there!
<FEEL FREE TO CHANGE THIS MESSAGE TO YOUR PERSONAL WORDS>

## Highlights
Used The Correct Font ✔️ 
Nice UI Design ✔️ 
Implemented Search Bar ✔️ 

## Suggested changes
_Check the comments under the review._

You can use as many of my suggestions as you want. If there is anything you would like to skip - feel free to do that. However, I strongly recommend you take them into account as they can make your code better._

You can also consider:
N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

2023-09-15 17:37 UTC, Munsa1 commented on README.md
> +  - [💻 Getting Started ](#-getting-started-)
- [ ] Kindly fix this broken link, clicking on it should take the user to the `Getting Started` section

2023-09-15 17:37 UTC, Munsa1 commented on README.md
> +    - [Usage](#usage)
- [ ] Kindly fix this broken link, clicking on it should take the user to the `Usage` part of the `Getting Started` section

2023-09-15 17:37 UTC, Munsa1 commented on README.md
> +  - [🔭 Future Features ](#-future-features-)
- [ ] Kindly fix these broken links, clicking on them should take the user to their appropriate sections

2023-09-15 17:37 UTC, Munsa1 commented on README.md
> +- Presentation [video](https://youtu.be/V495A_FApN0)
- [ ] Kindly ensure that the video presentation is not set to private so it can be viewed and feedback may be given
![image](https://github.com/firstpj/my-react-webapp/assets/81932478/9d8db7bb-55be-4850-8fe2-2d6833211eb7)

2023-09-15 17:37 UTC, Munsa1 commented on README.md
> +
- [ ] Kindly ensure the the `Acknowledgements section gives appropriate credit to [Nelson Sakwa](https://www.behance.net/sakwadesignstudio) the [author of the original design](https://www.behance.net/gallery/31579789/Ballhead-App-(Free-PSDs)), as required by the [Creative Commons License](https://creativecommons.org/licenses/).

2023-09-15 17:37 UTC, Munsa1 commented on src/component/Layout.jsx
> +export default Layout;
- [ ] Consider writing unit tests for this component as per requirement.

2023-09-15 17:37 UTC, Munsa1 commented on src/component/NavBar.jsx
> +);
- [ ] Again here consider writing a unit test for this component as per requirement.

2023-09-15 17:37 UTC, Munsa1 commented on src/component/WeatherCard.jsx
> +export default WeatherCard;
- [ ] Again here consider writing a unit test for this component as per requirement.

Example
```
import React from 'react';
import { render } from '@testing-library/react';
import WeatherCard from './WeatherCard';

test('renders the WeatherCard component', () => {
  const { getByText } = render(<WeatherCard />);
  
  // Assert that the text "WeatherCard" is present in the rendered component.
  const weatherCardElement = getByText('WeatherCard');
  expect(weatherCardElement).toBeInTheDocument();
});
```

2023-09-16 17:14 UTC, taldr27 requested changes
# Status: Required Changes ♻️♻️

Hi @firstpj, 

Great work on making the changes requested by a previous reviewer 👏 👏 
You've done well implementing some of the requested changes, but some are still not addressed yet.

![almost](https://media.giphy.com/media/t8YPf3ACKeouLzEIvr/giphy.gif)

## Highlights 🎉
✅ Professional Readme. 
✅ Linters passing.
✅ Good job adding your tests but not in the correct place.
✅ Incorporates feedback from previous code reviews.

 ## Required Changes ♻️
_Check the comments under the review._


------
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in @taldr27 your question so I can receive the notification.

If you need any further help or have any questions, feel free to reach out to me on Slack as _**Diego Garcia**_.🎯

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s). <img align="right" src="https://media.giphy.com/media/kReKcfrs1YoTmt2AQt/giphy.gif" alt="gif"  width="3%"/>_

2023-09-16 17:14 UTC, taldr27 commented on src/component/NavBar.jsx
> +});
- [ ] Good job adding your test as the previous reviewer asked, but please let's move the test to your tests folder and be sure that it passes correctly.

2023-09-16 17:14 UTC, taldr27 commented on src/component/Layout.jsx
> +  expect(LayoutElement).toBeInTheDocument();
- [ ] Good job adding your test as the previous reviewer asked, but please let's move the test to your tests folder and be sure that it passes correctly. Apply this suggestion for all your files, and don't forget that it's not a good practice to disable linters.

2023-09-16 20:17 UTC, cynthiainga requested changes
Hi @firstpj, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.

![](https://user-images.githubusercontent.com/57562869/143511358-9cde7daf-4ad0-4db2-8f15-18b54288ff91.gif)

 ## Highlights

- [ ] Correct Gitflow ✔️ 
- [ ] No linters errors ✔️ 
- [ ] Descriptive PR ✔️ 

 ## Required Changes ♻️

- [ ] Please kindly check the comment under the review 👇🏾 👇🏾 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you consider them as they can improve your code. Some of them were missed by the previous reviewer and addressing them will really improve your application._


Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-16 20:17 UTC, cynthiainga commented on src/component/WeatherCard.jsx
> +});
- [ ] As mentioned by the previous reviewer it would be nice to move your test to your test file and be sure that your tests are passing 🙃 😁

2023-09-16 20:51 UTC, Efiamotu-1 approved these changes
Hi @firstpj , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# STATUS: APPROVED 🕺🥳 

![image](https://user-images.githubusercontent.com/25227022/165483662-7b06c812-4cc0-40b9-a84c-4729d4cf10c3.gif)

## Highlights :dart: 
* Correct Gitflow :heavy_check_mark: 
* Good commit messages :heavy_check_mark: 
* All linters passing :heavy_check_mark: 
* Good PR summary :heavy_check_mark: 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

## Important Notes 📝

- Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
- Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

> **Note:** Please, you can now Merge since it is Approved ✅, However if there are any conflicts please resolve them before merging.


## Thank you for your time 🙏 and call me if you need help or clarification ☎️

- This is My **GitHub**: [![@Efiamotu-1](https://img.shields.io/github/followers/Efiamotu-1?label=Habeeb-Efiamotu-Musa&style=social)](https://github.com/Efiamotu-1/)
- This is My **linkedIn**.[![Habeeb Efiamotu Musa](https://img.shields.io/badge/linkedin-@Habeeb-crimson)](https://www.linkedin.com/in/musa-habeeb/)
- This is My **Twitter**: [![@EFYAMOTU](https://img.shields.io/twitter/follow/omarramoun?label=Habeeb-Efiamotu-Musa&style=social)](https://twitter.com/EFYAMOTU)
- This is My **Slack**: [![Habeeb Efiamotu Musa ](https://img.shields.io/badge/slack-@Habeeb-brightgreen)](https://slack.com)

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-20 15:52 UTC, merged